version: '3.8'

services:
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-aaxis}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-aaxis}
      POSTGRES_USER: ${POSTGRES_USER:-aaxis}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  web:
    image: nginx:latest
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - custom-php

  custom-php:
    container_name: custom-php
    build:
      context: .
      dockerfile: Dockerfile.custom-php
    volumes:
      - ./:/var/www/symfony

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  database_data:
